### ISSUE TITLE
Resize quirks when setting a max height

### ISSUE THREAD

**Issue by abel-sch** [Booreiland/responsive-pics#20]
When a desired height is entered this only seems to be used when the width of the original image is larger than the calculated width of a resized image.

You'd expect it to work differently; the newly calculated image to be restricted by the desired width and desired height (just like in background-size: contain)

**Comment by Twansparant** [comment]
Hi @abel-sch, I did some tests and I can't seem to reproduce this issue anymore with the latest version 1.4.0.
Could you try and verify if your max height does get applied correctly now?
Thanks!

**Comment by abel-sch** [comment]
I don't see any changes. Here's a screenshot that might clarify what happens:
![Screenshot 2022-01-13 at 10 27 41](https://user-images.githubusercontent.com/10962066/149302933-510bb003-6eb6-4024-9a50-13f71c89a136.png)

The top row uses:
`{!! ResponsivePics::get_picture($slide->image, 'xs-12 250, sm-12 250, md-12 350', 'm-lightbox-carousel__image') !!}`
All images should fit within the 12 cols so there's no reason for some images to be smaller.

The bottom row uses:
`{!! ResponsivePics::get_picture($slide->image, 'xs:0 250, sm:0 250, md:0 350', 'm-lightbox-carousel__image') !!}` 
Which does work for this purpose but doesn't restrain the width.

**Comment by Twansparant** [comment]
Could you delete the resized images that are being displayed?
It could be it won't regenerate the correct image since the filename (with the wrong size) already exists.

**Comment by abel-sch** [comment]
Re-adding the images sadly gives the same result (I double checked, Responsive Pics re-processed them)

**Comment by Twansparant** [comment]
Could you verify if the latest [1.4.3 release](https://github.com/Booreiland/responsive-pics/releases/tag/1.4.3), fixed your issue?
The issue was, if the requested width or height was larger then the image dimensions, it would preserve the image aspect ratio and apply it to the max width and max height, which could result in a smaller max height in this case. I verified it locally and it works for me:
![rp_max_width_max_height](https://user-images.githubusercontent.com/2317592/149363399-90c16e16-7ecf-4520-a498-2ffffbfd5d2b.png)
